const CATEGORIES = {
  BANKING: "BANKING",
  SECURITY: "SECURITY",
  OTP: "OTP",
  WORK: "WORK",
  JOB: "JOB",
  SHOPPING: "SHOPPING",
  DELIVERY: "DELIVERY",
  TRAVEL: "TRAVEL",
  BILLS: "BILLS",
  GOVERNMENT: "GOVERNMENT",
  EDUCATION: "EDUCATION",
  SOCIAL: "SOCIAL",
  NEWSLETTER: "NEWSLETTER",
  PROMOTIONS: "PROMOTIONS",
  PERSONAL: "PERSONAL",
  UNKNOWN: "UNKNOWN"
};

const CATEGORIES_LIST = Object.values(CATEGORIES);

module.exports = {
  CATEGORIES,
  CATEGORIES_LIST
};
